version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: simmodelling_redis
    ports:
      - "127.0.0.1:6379:6379" # Expose Redis-Port auf localhost für Sicherheit
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes # Persistenz aktivieren
    restart: always

  importer:
    build:
      context: ../..
      dockerfile: Database/Python/Dockerfile
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # Beachte: Redis verwendet in der Regel keine Benutzer/Passwörter wie PostgreSQL,
      # aber ein Passwort kann optional konfiguriert werden

volumes:
  redis_data: