# Example Docker Compose configuration to start a local PostgreSQL database
# and the Python import service.

version: '3.8'

services:
  db:
    image: postgres:13
    container_name: simmodelling_db
    ports:
      - "127.0.0.1:5432:5432" # Expose port to localhost for security
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=simdata
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  importer:
    build:
      context: ../..
      dockerfile: Database/Python/Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: simdata

volumes:
  postgres_data:
