name: Java Test

on:
  push:
    branches: [ main, work ]
  pull_request:
    branches: [ main, work ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download Test Dependencies
        run: |
          mkdir libs
          wget -q -P libs https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar
          wget -q -P libs https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
      - name: Compile Java sources and tests
        run: |
          mkdir -p build
          javac -d build -cp "Database/jar/*:libs/*" Database/*.java PV/*.java test/*.java
      - name: Run tests
        run: |
          java -cp "build:Database/jar/*:libs/*" org.junit.runner.JUnitCore AnyLogicDBUtilTest PVTest
