name: Java Test

on:
  push:
    branches: [ main, work ]
  pull_request:
    branches: [ main, work ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Compile Java sources
        run: |
          javac -cp "Database/hsqldb-2.7.4.jar:Database/poi-3.0-FINAL.jar:Database/poi-ooxml-full-5.0.0.jar" Database/*.java PV/*.java
      - name: Run DatabaseTest
        working-directory: Database
        run: |
          java -cp ".:hsqldb-2.7.4.jar:poi-3.0-FINAL.jar:poi-ooxml-full-5.0.0.jar" DatabaseTest "jdbc:hsqldb:mem:test"
